#!/bin/bash

USAGE="usage: ${0##*/} [product/url]
Compare original to cdn copies of URL

where:
    product/url is the url path starting with product (firefox or
                thunderbird)

options:
    -h|--help   show help"

# best source of CDNs is table at:
#   https://nagios.mozilla.org/sentry/
# then weed out the internal and not-used-for-updaters (like cloudfront)
#       $ curl -X GET -iL https://d2w2s2wlgxgbf6.cloudfront.net/pub/thunderbird/releases/34.0b1/update/linux-x86_64/zh-TW/thunderbird-33.0b1-34.0b1.partial.mar
#       HTTP/1.1 403 Forbidden
#       Content-Type: text/html
#       Content-Length: 52
#       Connection: keep-alive
#       Cache-Control: max-age=600
#       Date: Mon, 17 Nov 2014 20:40:03 GMT
#       Age: 340
#       X-Cache: Error from cloudfront
#       Via: 1.1 d516d46cbba2b0e65ff660966e025465.cloudfront.net (CloudFront)
#       X-Amz-Cf-Id: pEUK4x8rtr9VN2TdgNTC9BH3FKdyqg7Q3QhrSxHAnMHIIB4Tqd1zrg==
#
#       This property is not for updaters, only installers.

cdn_base_urls=(
    # first is authoritative master
    http://ftp.mozilla.org/pub
    # edgesuite.net is akami - 2 diff urls? who knows
    http://wildcard.cdn.mozilla.net.edgesuite.net/pub
    http://download-akamai.cdn.mozilla.net/pub
    # high winds
    http://cds.d6b5y3z2.hwcdn.net/pub
    # edge cast
    http://wpc.1237.edgecastcdn.net/pub
)

warn() { for m; do echo "$m" ; done 1>&2 ; }
die() { warn "$@"; exit 1; }
usage() { warn "$@" "${USAGE:-}"; test $# -eq 0; exit $? ; }

while test $# -gt 0; do
    case "$1" in
    -h|--help) usage ;;
    -*) usage "Unknown option '$1'" ;;
    *) break ;;
    esac
    shift 1
done

test $# -le 1 || usage "Wrong # arguments: '$#'"

# leave a dummy value in there
product="${1:-thunderbird/releases/34.0b1/update/linux-x86_64/zh-TW/thunderbird-33.0b1-34.0b1.partial.mar}"


for url in ${cdn_base_urls[*]}; do
    echo $url/$product
    # content length and last modified should be the same on all hosts
    # (etag is modified on hwcdn.net)
    curl -o /dev/null -vILH 'Host: download.cdn.mozilla.net' \
        $url/$product 2>&1 | egrep -i '^< (content-length|last-modified):'
done
exit $?
