# Global list of hosts and options
from master_fabric import _make_masters, _make_master_config
from master_fabric import check, checkconfig, show_revisions, reconfig, update

gMasters = [
        {'name': 'pm01-bm',
         'hostname': 'production-master01.build.mozilla.org',
         'master_dir': '/builds/buildbot/builder_master1',
         'bbcustom_dir': '/tools/buildbotcustom/buildbotcustom',
         'bbconfigs_dir': '/builds/buildbot/configs',
         'roles': ['build'],
        },
        {'name': 'pm01-sm',
         'hostname': 'production-master01.build.mozilla.org',
         'master_dir': '/builds/buildbot/scheduler_master',
         'bbcustom_dir': '/tools/buildbotcustom/buildbotcustom',
         'bbconfigs_dir': '/builds/buildbot/configs',
         'roles': ['scheduler'],
        },
        {'name': 'pm02-sm',
         'hostname': 'production-master02.build.mozilla.org',
         'master_dir': '/builds/buildbot/tests-scheduler',
         'bbcustom_dir': '/tools/buildbotcustom-0.8.0/buildbotcustom',
         'bbconfigs_dir': '/builds/buildbot/configs',
         'roles': ['scheduler'],
        },
        {'name': 'pm02-try',
         'hostname': 'production-master02.build.mozilla.org',
         'master_dir': '/builds/buildbot/try-trunk-master',
         'bbcustom_dir': '/tools/buildbotcustom-0.8.0/buildbotcustom',
         'bbconfigs_dir': '/builds/buildbot/configs',
         'roles': ['try'],
        },
        {'name': 'test-master01',
         'hostname': 'test-master01.build.mozilla.org',
         'master_dir': '/builds/buildbot/tests-master',
         'bbcustom_dir': '/tools/buildbotcustom/buildbotcustom',
         'bbconfigs_dir': '/builds/buildbot/configs',
         'roles': ['tests'],
        },
        {'name': 'test-master02',
         'hostname': 'test-master02.build.mozilla.org',
         'master_dir': '/builds/buildbot/tests-master',
         'bbcustom_dir': '/tools/buildbotcustom/buildbotcustom',
         'bbconfigs_dir': '/builds/buildbot/configs',
         'roles': ['tests'],
        },
        {'name': 'talos-master02',
         'hostname': 'talos-master02.build.mozilla.org',
         'master_dir': '/builds/buildbot/tests-master',
         'bbcustom_dir': '/tools/buildbotcustom/buildbotcustom',
         'bbconfigs_dir': '/builds/buildbot/configs',
         'roles': ['tests'],
        },
        _make_master_config('bm3', 'buildbot-master1.build.mozilla.org', 'build', '/builds/buildbot/build_master3'),
        _make_master_config('bm4', 'buildbot-master2.build.mozilla.org', 'build', '/builds/buildbot/build_master4'),
        _make_master_config('tm3', 'buildbot-master1.build.mozilla.org', 'tests', '/builds/buildbot/tests_master3'),
        _make_master_config('tm4', 'buildbot-master1.build.mozilla.org', 'tests', '/builds/buildbot/tests_master4'),
        _make_master_config('tm5', 'buildbot-master2.build.mozilla.org', 'tests', '/builds/buildbot/tests_master5'),
        _make_master_config('tm6', 'buildbot-master2.build.mozilla.org', 'tests', '/builds/buildbot/tests_master6'),
    ]

_make_masters(gMasters)
